### PR TITLE
Fix Potential Randomisation Bug

### LINKED ISSUE #37: Use hashlib for random seed in batch jitter
Python hash() not consistent.

### PR DESCRIPTION
**Pull request by cymox1**
Resolves #37

### CODE REVIEW

**Comment by onejgordon** [comment]
@cymox1 only file changed here is readme

**Comment by cymox1** [comment]
@onejgordon will finalize on this. It is still WIP

**Comment by cymox1** [comment]
@onejgordon this is ready for review

**Comment by onejgordon** [comment]
Looks good. Though checks failing:
ImportError: No module named pyparsing

**Pull request merged**
